ApplicationStrings = {
error_contactNameNotEmpty:"Contacter nom ne peut pas être vide",
error_mustBeValidEmail:"doit être une adresse e-mail valide nom",
error_productNameNotEmpty:"produit ne peut pas être vide",
label_about:"propos",
label_aboutP1:"Cette application est créée pour démontrer que vous pouvez créer des applications entièrement vérifiables, Themable, localisables Web en utilisant efficacement notre bibliothèque.",
label_aboutTitle:"A propos de cet exemple",
label_applicationTitle:"CRUD Exemple de système",
label_back:"Retour",
label_browse:"Parcourir",
label_cancel:"résilier",
label_dataDeleted:"données supprimées.",
label_dataSaved:"données sauvegardées.",
label_errorTitle:"application Erreur",
label_genderFemale:"Femme",
label_genderMale:"Homme",
label_genderUnknown:"Inconnu",
label_next:"Suivant",
label_ok:"OK",
label_productPrice:"Prix",
label_productType:"Type de produit",
label_productType_FamilyCar:"voiture familiale",
label_productType_RaceCar:"Voiture de course",
label_productType_Suv:"SUV",
label_requirements:"requise",
label_sales:"Démo",
label_save:"Sauvegarder",
label_selectTheme:"Choisissez un thème:",
lable_commonTasks:"Tâches courantes",
lable_contact:"contacter",
lable_contactEmail:"Contact email",
lable_contactName:"Contact Nom",
lable_contactPicture:"Contact Image",
lable_create:"Créer",
lable_dateOfBirth:"Date de naissance",
lable_find:"Trouver",
lable_gender:"Sexe",
lable_product:"produit",
lable_productName:"Nom du produit",
lable_productPicture:"Photos produit",
lable_productVideo:"Vidéo produit",
text_businessRequirement:"affaires exigence",
themeName_summerHawaii:"Summer Hawaii",
themeName_winterAlaska:"Winter Alaska",
title_editContact:"Modifier le contact",
title_editContactEmail:"Modifier Contact Courriel",
title_editContactName:"Modifier Contact Nom",
title_editContactPicture:"Modifier Contact Image",
title_editProduct:"Modifier le produit",
tooltip_About:"A propos de cette application",
tooltip_collapseLeft:"Réduire ou agrandir le panneau sur la gauche",
tooltip_collapseRight:"Réduire ou agrandir le panneau sur la droite",
tooltip_deleteModel:"Effacer les données de cette ligne",
tooltip_editModel:"Modifier cette ligne",
tooltip_Sales:"Événements de vente",
text_businessRequirementContent:"Nom du produit ne peut pas être une chaîne vide, avant et arrière espace blanc doit être équilibré",
text_contactNameBusinessRequirementContent:"Nom du contact ne peut pas être une chaîne vide, avant et arrière espace blanc doit être équilibré",
text_contactNameUIRequirement1:"Une. Quand un nouveau contact est créé, le nom du contact doit être vide sans message d'erreur affiché",
text_contactNameUIRequirement4:"4. Sauvegarder bouton ne doit pas permettre à l'utilisateur d'enregistrer un contact avec un nom vide",
text_emailBusinessRequirementContent:"Champ E-mail doit correspondre à toute l'entreprise de définition email regex",
text_emailUiRequirement1:"Une. Quand un nouveau contact est créé, email de contact doit être vide sans message d'erreur affiché",
text_emailUiRequirement2:"2. Lorsque la boîte d'édition électronique a perdu l'accent et la valeur n'est pas valide, un message d'erreur à côté de la zone d'édition",
text_uiRequirement:"Exigence de l'interface utilisateur",
text_uiRequirement1:"Une. Lorsqu'un nouveau produit est créé, le nom du produit doit être vide sans message d'erreur affiché",
text_uiRequirement2:"2. Lorsque l'entrée de l'utilisateur contient un espace, il doit être coupé sur les deux extrémités lorsque le focus boîte d'édition de nom perdu",
text_uiRequirement3:"3. Si après la coupe, la saisie de l'utilisateur est une chaîne vide, afficher un message d'erreur le nom de boîte d'édition à côté",
text_uiRequirement4:"4. Sauvegarder bouton ne doit pas permettre à l'utilisateur d'enregistrer un produit avec un nom vide",
month_Apr:"avril",
month_Aug:"août",
month_Dec:"décembre",
month_Feb:"février",
month_Jan:"janvier",
month_Jul:"juillet",
month_Jun:"juin",
month_Mar:"mars",
month_May:"mai",
month_Nov:"novembre",
month_Oct:"octobre",
month_Sept:"septembre",
day_Fri:"vendredi",
day_Mon:"lundi",
day_Sat:"samedi",
day_Sun:"dimanche",
day_Thur:"jeudi",
day_Tue:"mardi",
day_Wed:"mercredi",
label_documentation:"documentation",
tooltip_documentation:"Bibliothèque de documentation en anglais"};
