YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "a",
        "acceptType",
        "area",
        "article",
        "asynCallParam",
        "asyncGetCall",
        "asyncPostCall",
        "audio",
        "barChart",
        "bdo",
        "bindButtonCommand",
        "bindFileProperty",
        "bindProperty",
        "body",
        "br",
        "button",
        "canvas",
        "caption",
        "chartBase",
        "checkBox",
        "collectionModelBase",
        "columnChart",
        "command",
        "containerElement",
        "customEvent",
        "d3BubbleChart",
        "d3Charting",
        "datetimeInput",
        "decentMouseEvent",
        "dialogButtonRow",
        "dialogSkeleton",
        "dialogTitleRow",
        "div",
        "divButton",
        "documentElement",
        "element",
        "embed",
        "enumMouseButton",
        "fieldset",
        "figCaption",
        "figure",
        "fileBrowseButton",
        "fileHandlingModelFactory",
        "fileInput",
        "filePropertyModel",
        "fileTypeModel",
        "fileValueModel",
        "floatInput",
        "footer",
        "form",
        "formPost",
        "guid",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "header",
        "hr",
        "hybridMap",
        "iframe",
        "img",
        "inputElement",
        "intInput",
        "keygen",
        "label",
        "legend",
        "li",
        "lineChart",
        "link",
        "map",
        "mapBase",
        "modalDialog",
        "modelBase",
        "modelFactory",
        "multiFilePropertyModel",
        "numericInput",
        "objectElement",
        "observable",
        "observableCollection",
        "ol",
        "optGroup",
        "option",
        "p",
        "param",
        "pieChart",
        "popup",
        "popupMoveHandler",
        "position",
        "radioButton",
        "restCallBase",
        "restDelete",
        "restGet",
        "restGetAll",
        "restPost",
        "restPut",
        "roadMap",
        "satelliteMap",
        "scrollPanel",
        "select",
        "serviceProxy",
        "size",
        "source",
        "span",
        "spanText",
        "svg",
        "table",
        "tbody",
        "td",
        "terrainMap",
        "textArea",
        "textBlock",
        "textInput",
        "textNode",
        "tfoot",
        "th",
        "thead",
        "touchEvent",
        "tr",
        "track",
        "ul",
        "valueContainer",
        "valueElement",
        "video",
        "windowElement",
        "windowOverlay"
    ],
    "modules": [
        "D3Chart",
        "advanced",
        "comm",
        "controls",
        "elements",
        "googleCharts",
        "googleMaps",
        "observe"
    ],
    "allModules": [
        {
            "displayName": "advanced",
            "name": "advanced",
            "description": "Provides advanced user interface controls available through a commercial license"
        },
        {
            "displayName": "comm",
            "name": "comm",
            "description": "Provides classes for client server communication"
        },
        {
            "displayName": "controls",
            "name": "controls",
            "description": "Provides reusable user interface controls"
        },
        {
            "displayName": "D3Chart",
            "name": "D3Chart",
            "description": "An example chart class that draws a bubble chart using d3 library. Content of this class is based on example provided by d3: http://bl.ocks.org/mbostock/4063269. Copyright owned by original creator and d3."
        },
        {
            "displayName": "elements",
            "name": "elements",
            "description": "Provides classes for constructing basic DOM elements"
        },
        {
            "displayName": "googleCharts",
            "name": "googleCharts",
            "description": "A barChart"
        },
        {
            "displayName": "googleMaps",
            "name": "googleMaps",
            "description": "A hybridMap."
        },
        {
            "displayName": "observe",
            "name": "observe",
            "description": "Provides classes to support data binding, command binding, and event notification"
        }
    ]
} };
});