ApplicationStrings = {
label_about:"About",
label_aboutP1:"This application is created to demonstrate that you can create fully testable, themable, localizable web applications efficiently using our library.",
label_aboutTitle:"About this example",
label_applicationTitle:"CRUD System Example",
label_back:"Back",
label_cancel:"Cancel",
label_next:"Next",
label_ok:"OK",
label_sales:"Demo",
label_selectTheme:"Select a theme:",
themeName_summerHawaii:"Summer Hawaii",
themeName_winterAlaska:"Winter Alaska",
tooltip_About:"About this application",
tooltip_collapseLeft:"Collapse or expand panel on the left",
tooltip_collapseRight:"Collapse or expand panel on the right",
tooltip_Sales:"Sales events",
lable_commonTasks:"Common Tasks",
lable_contact:"Contact",
lable_create:"Create",
lable_find:"Find",
lable_product:"Product",
label_save:"Save",
lable_productName:"Product Name",
label_errorTitle:"Application Error",
label_dataSaved:"Data saved.",
error_productNameNotEmpty:"Product name cannot be empty",
error_contactNameNotEmpty:"Contact name cannot be empty",
error_mustBeValidEmail:"Must be a valid email address",
label_requirements:"Requirements",
text_businessRequirement:"Business requirement",
text_businessRequirementContent:"Product name cannot be empty string, leading and trailing white space must be trimmed",
text_uiRequirement:"User interface requirement",
text_uiRequirement1:"1. When a new product is created, product name must be empty with no error message shown",
text_uiRequirement2:"2. When user input contains white space, it must be trimmed on both ends when name edit box lost focus",
text_uiRequirement3:"3. If after trimming, the user input is empty string, display an error message beside name edit box",
text_uiRequirement4:"4. Save button should not allow user to save a product with empty name",
lable_contactEmail:"Contact EMail",
lable_contactName:"Contact Name",
text_contactNameBusinessRequirementContent:"Contact name cannot be empty string, leading and trailing white space must be trimmed",
text_contactNameUIRequirement1:"1. When a new contact is created, contact name must be empty with no error message shown",
text_contactNameUIRequirement4:"4. Save button should not allow user to save a contact with empty name",
text_emailBusinessRequirementContent:"Email field must match companywide email regex definition",
text_emailUiRequirement1:"1. When a new contact is created, contact email must be empty with no error message shown",
text_emailUiRequirement2:"2. When email edit box lost focus and the value is invalid, display an error message beside the edit box",
tooltip_deleteModel:"Delete data in this row",
tooltip_editModel:"Edit data in this row",
title_editProduct:"Edit Product",
title_editContact:"Edit Contact",
label_dataDeleted:"Data deleted.",
title_editContactEmail:"Edit Contact Email",
title_editContactName:"Edit Contact Name",
lable_productPicture:"Product Pictures",
lable_contactPicture:"Contact Picture",
title_editContactPicture:"Edit Contact Picture",
label_browse:"Browse",
lable_productVideo:"Product Video",
label_productPrice:"Price",
label_productType:"Product Type",
label_productType_FamilyCar:"Family Car",
label_productType_RaceCar:"Race Car",
label_productType_Suv:"SUV",
label_genderFemale:"Female",
label_genderMale:"Male",
label_genderUnknown:"Unknown",
lable_dateOfBirth:"Date of Birth",
lable_gender:"Gender",
month_Apr:"April",
month_Aug:"August",
month_Dec:"December",
month_Feb:"February",
month_Jan:"January",
month_Jul:"July",
month_Jun:"June",
month_Mar:"March",
month_May:"May",
month_Nov:"November",
month_Oct:"October",
month_Sept:"September",
day_Fri:"Fri.",
day_Mon:"Mon.",
day_Sat:"Sat.",
day_Sun:"Sun.",
day_Thur:"Thur.",
day_Tue:"Tue.",
day_Wed:"Wed.",
label_documentation:"Documentation",
tooltip_documentation:"Library documentation in English"};
